"""Initial try

Revision ID: 892582a7a271
Revises: 
Create Date: 2024-07-30 12:32:49.459675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892582a7a271'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admin_admin_id'), 'admin', ['admin_id'], unique=False)
    op.create_table('agent',
    sa.Column('agent_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agent_agent_id'), 'agent', ['agent_id'], unique=False)
    op.create_table('employee',
    sa.Column('employee_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employee_employee_id'), 'employee', ['employee_id'], unique=False)
    op.create_table('insuranceplan',
    sa.Column('plan_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('plan_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_insuranceplan_plan_id'), 'insuranceplan', ['plan_id'], unique=False)
    op.create_table('customer',
    sa.Column('customer_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agent_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customer_customer_id'), 'customer', ['customer_id'], unique=False)
    op.create_table('scheme',
    sa.Column('scheme_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scheme_name', sa.String(length=100), nullable=True),
    sa.Column('scheme_details', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scheme_tenure', sa.Integer(), nullable=False),
    sa.Column('scheme_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['insuranceplan.plan_id'], ),
    sa.PrimaryKeyConstraint('scheme_id')
    )
    op.create_index(op.f('ix_scheme_scheme_id'), 'scheme', ['scheme_id'], unique=False)
    op.create_table('employeescheme',
    sa.Column('employeescheme_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('scheme_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.scheme_id'], ),
    sa.PrimaryKeyConstraint('employeescheme_id')
    )
    op.create_index(op.f('ix_employeescheme_employeescheme_id'), 'employeescheme', ['employeescheme_id'], unique=False)
    op.create_table('policy',
    sa.Column('policy_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('scheme_id', sa.BigInteger(), nullable=False),
    sa.Column('policy_details', sa.Text(), nullable=False),
    sa.Column('premium', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('maturity_period', sa.Integer(), nullable=False),
    sa.Column('policy_lapse_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.scheme_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_policy_policy_id'), 'policy', ['policy_id'], unique=False)
    op.create_table('commission',
    sa.Column('commission_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('policy_id', sa.BigInteger(), nullable=False),
    sa.Column('commission_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agent_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.policy_id'], ),
    sa.PrimaryKeyConstraint('commission_id')
    )
    op.create_index(op.f('ix_commission_commission_id'), 'commission', ['commission_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('policy_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.policy_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_payment_id'), 'payment', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_commission_commission_id'), table_name='commission')
    op.drop_table('commission')
    op.drop_index(op.f('ix_policy_policy_id'), table_name='policy')
    op.drop_table('policy')
    op.drop_index(op.f('ix_employeescheme_employeescheme_id'), table_name='employeescheme')
    op.drop_table('employeescheme')
    op.drop_index(op.f('ix_scheme_scheme_id'), table_name='scheme')
    op.drop_table('scheme')
    op.drop_index(op.f('ix_customer_customer_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_insuranceplan_plan_id'), table_name='insuranceplan')
    op.drop_table('insuranceplan')
    op.drop_index(op.f('ix_employee_employee_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_agent_agent_id'), table_name='agent')
    op.drop_table('agent')
    op.drop_index(op.f('ix_admin_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
